<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoriaRequest;
use App\Http\Requests\ProdutoRequest;
use App\Http\Requests\TipoPagamentoRequest;
use Illuminate\Support\Facades\DB;

class ProdutosController extends Controller
{
    public $model = "Produtos";

    public function __construct()
    {
        $this->_title = "Produtos";

        parent::__construct();
    }

    public function save(ProdutoRequest $request)
    {
        try {
            DB::transaction(function () use ($request) {
                $data = $this->_model->_save($request->all());
            });

            $response['status'] = true;
        } catch (\Exception $e) {
            $response['message'] = $e->getMessage();
        }

        return response()->json($response);
    }

    public function edicao($id = null)
    {
        $view = parent::edicao($id); // TODO: Change the autogenerated stub
        $view->model->preco = number_format($view->model->preco, 2, ",", ".");
        return $view;
    }
}
